### ISSUE TITLE
User not changing location

### ISSUE THREAD

**Issue by pperle** [OpenPoGo/OpenPoGoWeb#183]
The user is not chaning location, he is stuck to his original position.

The Error code from the debug console:
`socket.io-1.4.5.js:1 GET http://192.168.104.130:8000/socket.io/?EIO=3&transport=polling&t=LPu-2SA 404 (File not found)`

**Comment by youberser** [comment]
Same for me

**Comment by meganoob1337** [comment]
+1

**Comment by abel-n** [comment]
Same for me, I found some comment on the map not working with PokemonGo-Bot, though. Not 100% sure.

_EDIT_
Explained more: As @meganoob1337 said after me, most of the features work fine, but the trainer location isn't updating. (thus the is no path drawn neither)

**Comment by meganoob1337** [comment]
Hmm the bot is working fine , and it displays the stats and all , even the pokemon appear , just the trainer icon doesn't move :(

**Comment by silva96** [comment]
same here

**Comment by BobbyWibowo** [comment]
@theLastLivingGhost This repo will most likely transit to support OpenPoGoBot only. If you're using PokemonGo-Bot, you can try my fork. Although I'll most likely stop using it in the future, so I can't guarantee that it'll remain developed, but it should work great with PokemonGo-Bot for the time being.

@everyone_else Try OpenPoGoBot if you're getting similar error message as the OP.

**Comment by pperle** [comment]
I'm gettign the same error messengaes but I fixed the not following issue.

Uncomment 

``` python
 # while True:
 #     self.web_update_queue.get()
 #     self.update_web_location()
```

in  `pokemongo_bot/ _init__.py`

https://github.com/PokemonGoF/PokemonGo-Bot/commit/41de6f7250f408e51e49ff0380b029f0a3e9632e#diff-a8e82d1c2066f1b62d2f396a4e0e585bL994

**Comment by silva96** [comment]
@chuparCh0pper it works with your fix, thanks

**Comment by youberser** [comment]
@chuparCh0pper Mine gives me an error... 

```
"Unexpected Intent" 
line 1007
    while True:
```

**Comment by youberser** [comment]
@BobbyWibowo Im testing your web plugin but the problem still there.... I dont see the bot moving around, it just stay at the same site

**Comment by silva96** [comment]
@chuparCh0pper now the fix makes the distance empty

```
[13:18:48] Moving towards pokestop Instituto Confucio - 0.09km
[13:18:48] {'distance_unit': '', 'distance': '', 'current_position': (-33.442803022429835, -70.66315780035433), 'last_position': (-33.44282336361273, -70.66313832839448)}
```

```
2016-08-11 13:18:50,457 [       cli] [INFO] Ran for 0:01:17
2016-08-11 13:18:50,457 [       cli] [INFO] Total XP Earned: 150  Average: 6980.14/h
2016-08-11 13:18:50,457 [       cli] [INFO] Travelled 0.00km
```

**Comment by pperle** [comment]
Since this is not a web error please leave any error messages here https://github.com/PokemonGoF/PokemonGo-Bot/issues/3546

@silva96 let it run for a bit 10 minutes and there should be a distance

**Comment by BobbyWibowo** [comment]
@youberser wchill/refactor branch, right?

**Comment by youberser** [comment]
@BobbyWibowo I made a mistake, forgot to comment "pass" on init.py
Now works perfect!

**Comment by silva96** [comment]
@chuparCh0pper nope, the distance is not being shown in the logs, `{'distance_unit': '', 'distance': ''`

not even after 10 miutes
